call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/org.eclipse.core.commands_3.6.100.v20140528-1422.jar"           -Dsources="../lib/provided/src/org.eclipse.core.commands.source_3.6.100.v20140528-1422.jar"                 -DgroupId=org.eclipse.core    -DartifactId=org.eclipse.core.commands  -Dpackaging=jar -DcreateChecksum=true -Dversion=3.6.100.v20140528-1422
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/org.eclipse.equinox.common_3.6.200.v20130402-1505.jar"          -Dsources="../lib/provided/src/org.eclipse.equinox.common.source_3.6.200.v20130402-1505.jar"                -DgroupId=org.eclipse.equinox -DartifactId=org.eclipse.equinox.common -Dpackaging=jar -DcreateChecksum=true -Dversion=3.6.200.v20130402-1505
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/org.eclipse.jface_3.10.2.v20141021-1035.jar"                    -Dsources="../lib/provided/src/org.eclipse.jface.source_3.10.2.v20141021-1035.jar"                          -DgroupId=org.eclipse         -DartifactId=org.eclipse.jface          -Dpackaging=jar -DcreateChecksum=true -Dversion=3.10.2.v20141021-1035
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/platform/cocoa-macosx-x86_64/swt-4.5.2-cocoa-macosx-x86_64.jar" -Dsources="../lib/provided/platform/cocoa-macosx-x86_64/src/swt-4.5.2-cocoa-macosx-x86_64-src.zip"          -DgroupId=org.eclipse         -DartifactId=swt                        -Dpackaging=jar -DcreateChecksum=true -Dversion=4.5.2-cocoa-macosx-x86_64
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/platform/gtk-linux-armhf/swt-4.3.2-gtk-linux-armhf.jar"                                                                                                                     -DgroupId=org.eclipse         -DartifactId=swt                        -Dpackaging=jar -DcreateChecksum=true -Dversion=4.3.2-gtk-linux-armhf
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/platform/gtk-linux-x86/swt-4.5.2-gtk-linux-x86.jar"             -Dsources="../lib/provided/platform/gtk-linux-x86/src/swt-4.5.2-gtk-linux-x86-src.zip"                      -DgroupId=org.eclipse         -DartifactId=swt                        -Dpackaging=jar -DcreateChecksum=true -Dversion=4.5.2-gtk-linux-x86
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/platform/gtk-linux-x86_64/swt-4.5.2-gtk-linux-x86_64.jar"       -Dsources="../lib/provided/platform/gtk-linux-x86_64/src/swt-4.5.2-gtk-linux-x86_64-src.zip"                -DgroupId=org.eclipse         -DartifactId=swt                        -Dpackaging=jar -DcreateChecksum=true -Dversion=4.5.2-gtk-linux-x86_64
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/platform/win32-win32-x86/swt-4.5.2-win32-win32-x86.jar"         -Dsources="../lib/provided/platform/win32-win32-x86/src/swt-4.5.2-win32-win32-x86-src.zip"                  -DgroupId=org.eclipse         -DartifactId=swt                        -Dpackaging=jar -DcreateChecksum=true -Dversion=4.5.2-win32-win32-x86
call mvn install:install-file -DlocalRepositoryPath="./" -Dfile="../lib/provided/platform/win32-win32-x86_64/swt-4.5.2-win32-win32-x86_64.jar"   -Dsources="../lib/provided/platform/win32-win32-x86_64/src/swt-4.5.2-win32-win32-x86_64-src.zip"            -DgroupId=org.eclipse         -DartifactId=swt                        -Dpackaging=jar -DcreateChecksum=true -Dversion=4.5.2-win32-win32-x86_64
